config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks'}
  resources :users do
    resources :meals do

    end
  end

  resources :users do
    resources :workouts do

    end
  end

  get 'users/auth/spotify/callback', to: 'users#spotify'

# get 'new'
# post 'create'
# get 'edit'
# post 'update'
# get 'index'
# post 'destory'

  root 'landing#index'
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :user
  include PublicActivity::Model
  tracked
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def index
    @workouts = Workout.all
    user_id = current_user.id
  end

  def new
    @workout = Workout.new
    @upper_body_options = ["Pull Ups", "Bench Press", "Shrugs", "Shoulder Press", "Upright Rows"]
    @lower_body_options = ["Squats", "Deadlifts", "Lunges", "Calf Raises", "Reverse Hypers"]
    @cardio_options = ["Sprints", "Walking", "Jog", "Treadmill", "Bike Ride"]
  end

  def create
    @workouts = Workout.new(workout_params)
    if @workouts.save
      redirect_to user_workouts_path(current_user.id)
    else
      format.html { render :new }
      format.json { render json: @user.errors, status: :unprocessable_entity}
    end
  end

  def update
    respond_to do |format|
      if @workouts.update(workout_params)
        format.html { redirect_to @workouts, notice: 'Workout was successfully updated.'}
        format.json { render :show, status: :ok, location: @workouts }
      else
        format.html { render :edit }
        format.json { render json: @workouts.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @workouts.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  private

  def set_workout
   @workout = Workout.find(params[:id])
  end

  def workout_params
    params.require(:workout).permit(:cardio, :upper_body, :lower_body)
  end


end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/index.html.erb
<div class="container">
        <div class="navbar navbar-inverse navbar-static-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#homepage"><%= link_to "Spartan", users_path %>

              </a>
            </div>
            <div class="navbar-collapse collapse">
              <div class="right-inner-addon pull-right">

              </div>
              <ul class="nav navbar-nav">
                <li class="active"></li>
                <li><a href="#workouts"><%= link_to "", new_user_workout_path(current_user.id, @workouts), class: "fa fa-bicycle fa-2x" %></a></li>
                <li><a href="#meals"><%= link_to "", new_user_meal_path(current_user.id, @meals), class: "fa fa-cutlery fa-2x" %></a></li>
                <li><a href="signout"><%= link_to '', destroy_user_session_path, method: :delete, class: "fa fa-sign-out fa-2x" %></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  <h2>List of Workouts</h2>

<div class="features">
  <div class="workout-features">
    <h3>Pull Ups</h3>
      <p>Make sure to focus on pulling yourself completely up to the bar, repeat until failure with neutral or wide-grip. Targets the latisumus dorsi.</p>
  </div>
  <div class="workout-features">
    <h3>Bench Press</h3>
      <p>Pinch scapulas back and keep elbows pointed inward, complete 4 sets of 6. Excellent for development of the pectoralis major and triceps.</p>
  </div>
  <div class="workout-features">
    <h3>Shrugs</h3>
      <p>Can be done with a barbell or dumbells. These are to never move and need to be held with a firm grip. Ensure to have shoulders completely relaxed at start of lift. With a shrugging motion bring shoulders upward towards ears. Excellent way to develop stronger traps, shoulders and neck.</p>
  </div>
  <div class="workout-features">
    <h3>Shoulder Press</h3>
      <p>Can be done with a barbell or dumbells. Sit in bench with back support in upright position. Begin lift with weight lowered on chest and extend in upward pressing motion. This is a sure fire way to develop stronger deltoids.</p>
  </div>
  <div class="workout-features">
    <h3>Upright Rows</h3>
      <p>Best to complete this exercise with a barbell but can be done with dumbells. Stand up and hold bar towards center in front of your body. As you bring bar up to chin, it is important to keep elbows pointing outward as you maintain grip. This exercise has a great all-around benefit to developing the shoulders.</p>
  </div>
  <div class="workout-features">
    <h3>Squats</h3>
      <p>Probably the easiest workout to do incorrectly so it is important to practice correct form prior to doing any real weight. The benefit of this exercise is tremendous as it requires the entire core and lower body to do. Ensure to push hips back prior to descent while keeping chest up. A "true" squat is considered breaking parallel. If you cannot do this then it is not recommended to attempt to break parallel.</p>
  </div>
  <div class="workout-features">
    <h3>Deadlifts</h3>
      <p>Deadlifts are an outstanding way to develop the posterior. Ensure you have bar held in alternate grip. Begin lift with pushing through the floor as you extend to stand. Technique is extremely important with this exercise because if done incorrectly it can lead to serious injury.</p>
  </div>
  <div class="workout-features">
    <h3>Lunges</h3>
      <p>Can be done with a barbell or dumbells and by walking forward or being stationary. As you hold weight, lift foot up and out and lunge forward. Make sure not to overextend and keep your center of balance. This develops the hamstrings and glutes.</p>
  </div>
  <div class="workout-features">
    <h3>Calf Raises</h3>
      <p>These can be done standing with dumbells or by using a leg press machine while seated. It is important to keep foot flat before proceeding to plantar flexion. Develops both the gastrocnemius and soleus muscles.</p>
  </div>
  <div class="workout-features">
    <h3>Reverse Hypers</h3>
      <p>Excellent way to develop posterior. Ensure legs are free as upper body is laying on abdomen. Can be done while holding med ball between legs if advanced.</p>
  </div>


  <div class="workout-features">
    <h3>Sprints</h3>
      <p>A great way to develop speed. This can be done over a range of distances. If you are a beginner it is very important to use proper biomechanics. Start with 10 yards and progress to 30.</p>
  </div>
  <div class="workout-features">
    <h3>Walking</h3>
      <p>Beneficial in every sense of the word. Pace can vary depending on goal.</p>
  </div>
  <div class="workout-features">
    <h3>Jog</h3>
      <p>Pace can vary and be done at whichever distance desired.</p>
  </div>
  <div class="workout-features">
    <h3>Treadmill</h3>
      <p>Provides a great way to focus on cardio by adjusting settings and is ideal when dealing with inclimate weather.</p>
  </div>
  <div class="workout-features">
    <h3>Bike Ride</h3>
      <p>Excellent way to develop lower body strength while improving cardio.</p>
  </div>

app/views/workouts/new.html.erb
<div class="navbar-wrapper">
      <div class="container">
        <div class="navbar navbar-inverse navbar-static-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#homepage"><%= link_to "Spartan", users_path %>
              </a>
            </div>
            <div class="navbar-collapse collapse">
              <div class="right-inner-addon pull-right">

              </div>
              <ul class="nav navbar-nav">
                <li class="active"></li>
                <li><a href="#workouts"><%= link_to "", user_workouts_path(current_user.id, @workouts), class: "fa fa-bicycle fa-2x" %></a></li>
                <li><a href="#meals"><%= link_to "", new_user_meal_path(current_user.id, @meals), class: "fa fa-cutlery fa-2x" %></a></li>
                <li><a href="signout"><%= link_to '', destroy_user_session_path, method: :delete, class: "fa fa-sign-out fa-2x" %></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

  <div class="workout-selector">
    <h2>Select Your Workout</h2>
      <div id="form-group">
        <%= simple_form_for([current_user, @workout] ) do |f| %>
      </div>
        <div class="form-inputs">
          <%= f.select :cardio, @cardio_options %>
          <%= f.select :upper_body, @upper_body_options %>
          <%= f.select :lower_body, @lower_body_options %>
        </div>

        <%= f.submit %>
      </button>
    <% end %>

  </div>
<h2>Be Inspired. Let's get better today.</h2>
<div class="workout-image">
  <img class="image-displayed" src="https://pbs.twimg.com/media/Bs_xSV9CYAAKxgs.jpg" alt>

</div>